all: cyoa-step1 cyoa-step2 cyoa-step3 cyoa-step4

cyoa-step1: cyoa-step1.cpp
	clang++ -o cyoa-step1 -std=gnu++98 -Wall -Werror -ggdb3 cyoa-step1.cpp

cyoa-step2: cyoa-step2.cpp
	clang++ -o cyoa-step2 -std=gnu++98 -Wall -Werror -ggdb3 cyoa-step2.cpp

cyoa-step3: cyoa-step3.cpp
	clang++ -o cyoa-step3 -std=gnu++98 -Wall -Werror -ggdb3 cyoa-step3.cpp

cyoa-step4: cyoa-step4.cpp
	clang++ -o cyoa-step4 -std=gnu++98 -Wall -Werror -ggdb3 cyoa-step4.cpp

clean:
	rm -f *~ cyoa-step1 cyoa-step2 cyoa-step3 cyoa-step4
